# マウス入力有効化
set -g mouse on

# Neovimのモード切替で遅延が出るのを直す
set -sg escape-time 10

# コピーモード (vi) を有効化
set-window-option -g mode-keys vi

# クリップボード共有の有効化
set -s set-clipboard on
set -as terminal-features ',xterm-256color:clipboard'
set -s allow-passthrough on
